// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCW_t5LhyZxiIREnT0hOuTW3gcoDHppgU',
    appId: '1:254447511408:web:1de9b5eb777a5c0fb5d1b5',
    messagingSenderId: '254447511408',
    projectId: 'what-chat-80781',
    authDomain: 'what-chat-80781.firebaseapp.com',
    storageBucket: 'what-chat-80781.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0UsbwV52sN4pKFqX7fMdNiEpvy5ssDm8',
    appId: '1:254447511408:android:3604d6da7f84431eb5d1b5',
    messagingSenderId: '254447511408',
    projectId: 'what-chat-80781',
    storageBucket: 'what-chat-80781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbSMSveV7sqRwNbLdi9XDpirKNkKG49Bs',
    appId: '1:254447511408:ios:efac7d6b4a5c84cbb5d1b5',
    messagingSenderId: '254447511408',
    projectId: 'what-chat-80781',
    storageBucket: 'what-chat-80781.appspot.com',
    iosBundleId: 'com.example.whatChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbSMSveV7sqRwNbLdi9XDpirKNkKG49Bs',
    appId: '1:254447511408:ios:0d1cddfdccb1f3c9b5d1b5',
    messagingSenderId: '254447511408',
    projectId: 'what-chat-80781',
    storageBucket: 'what-chat-80781.appspot.com',
    iosBundleId: 'com.example.whatChat.RunnerTests',
  );
}
